[build]
target = "./docs/index.html"
public_url = "./"
release = true
manifest-path = "./docs/Cargo.toml"
minify = "on_release"
filehash = true

[tools]
wasm_opt = "version_120"

[watch]
watch = ["./docs/src", "./docs/static", "./docs/index.html", "./docs/globals.css", "./docs/tailwind.config.ts", "./tailwind.config.ts"]
ignore = ["dist", "target"]

[serve]
port = 8080
open = true
# Enable CORS for development
cors = true

[clean]
cargo = true
