[build]
target = "./docs/index.html"
public_url = "/"
release = true
manifest-path = "./docs/Cargo.toml"
minify = "never"

[watch]
watch = ["./docs/src", "./docs/static"]
ignore = ["dist", "target"]

[serve]
port = 8080
open = true
# Enable CORS for development
cors = true

[clean]
cargo = true
