[package]
name = "momenta-router"
version = "0.1.0"
edition = "2024"

[dependencies]
momenta = { path = "../momenta" }
matchit = "0.8"
web-sys = { version = "0.3", features = ["Window", "Location", "History", "Event", "PopStateEvent", "EventTarget"] }
wasm-bindgen = "0.2"
