[package]
name = "simple-rsx"
version = "0.1.3"
edition = "2024"
description = "A simple JSX-like syntax implementation for Rust"
authors = ["Jonathan Irhodia <jonathanirhodia@gmail.com>"]
license = "MIT"
repository = "https://github.com/elcharitas/simple-rsx"
keywords = ["jsx", "react", "template", "markup", "html"]
categories = ["template-engine", "web-programming", "markup"]
documentation = "https://docs.rs/simple-rsx"

[dependencies]
simple-rsx-macros = { path = "../simple-rsx-macros", version = "0.1.3" }
