[package]
name = "docs"
version = "0.1.0"
edition = "2024"
metadata.workspace = true

[dependencies]
simple-rsx = { path = "../simple-rsx", features = ["wasm"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
